### ISSUE TITLE
Cant Launch main.py

### ISSUE THREAD

**Issue by ajalloul** [Pycomet/escrow-service-bot#13]
Hey. I am trying to launch the project from main.py after following your setup instructions. Ive been facing the following issues. Please advise. 

<img width="845" alt="Screen Shot 2020-10-20 at 22 13 24" src="https://user-images.githubusercontent.com/41988631/96579410-89fff180-1322-11eb-9fe2-f3b1e21d68c0.png">

<img width="743" alt="Screen Shot 2020-10-20 at 22 13 45" src="https://user-images.githubusercontent.com/41988631/96579419-8d937880-1322-11eb-9009-c277db8d9e02.png">

I'm using VS code, BTC payserver and a telegram bot. Python version 3.6 with VS Code.

**Comment by Pycomet** [comment]
Thank you for using my application 😃, I am ready to give my support at any time.

I’m pretty sure the error is because the dependencies were not installed completely. You can retry “pip install -r requirements.txt” without errors to complete the download.

Please do not forget to star the repo too 👍🏾

Alfred
www.coffered.me
